/* eslint-disable import/prefer-default-export */

export const SET_EMAIL = 'persona/SET_EMAIL'
export const SET_EMAIL_ERROR = 'persona/SET_EMAIL_ERROR'
export const CLEAR_EMAIL_ERROR = 'persona/CLEAR_EMAIL_ERROR'
export const SET_PASSWORD = 'persona/SET_PASSWORD'
export const SET_CONFIRM_PASSWORD = 'persona/SET_CONFIRM_PASSWORD'
export const SET_OLD_PASSWORD = 'persona/SET_OLD_PASSWORD'
export const SET_PASSWORD_ERROR = 'persona/SET_PASSWORD_ERROR'
export const CLEAR_PASSWORD_ERROR = 'persona/CLEAR_PASSWORD_ERROR'
export const SET_NEW_PASSWORD_ERROR = 'persona/SET_NEW_PASSWORD_ERROR'
export const CLEAR_NEW_PASSWORD_ERROR = 'persona/CLEAR_NEW_PASSWORD_ERROR'
export const CLEAR_CREDENTIALS = 'persona/CLEAR_CREDENTIALS'
export const AUTH_RUNTIME_CACHE = 'persona/AUTH_RUNTIME_CACHE'

export const STORE_PERSONA = 'persona/STORE_PERSONA'
export const STORE_SESSION = 'persona/STORE_SESSION'
export const SET_LOADING = 'persona/SET_LOADING'
export const SET_NUMBER_UNREAD_MESSAGE = 'persona/SET_NUMBER_UNREAD_MESSAGE'
export const SET_NUMBER_UNREAD_THREAD = 'persona/SET_NUMBER_UNREAD_THREAD'
export const SAVE_ACTIVE_PERSONA_DEMO_MODE = 'persona/SAVE_ACTIVE_PERSONA_DEMO_MODE'
export const SAVE_SESSION_DEMO_MODE = 'persona/SAVE_SESSION_DEMO_MOD'
export const RESTORE_ACTIVE_PERSONA_DEMO_MODE = 'persona/RESTORE_ACTIVE_PERSONA_DEMO_MODE'
export const RESTORE_SESSION_DEMO_MODE = 'persona/RESTORE_SESSION_DEMO_MODE'
export const SAVE_PUSH_NOTIFICATION_INFO = 'persona/SAVE_PUSH_NOTIFICATION_INFO'
export const SAVE_BEHAVIOR_REPORTS_SUSTAINED = 'persona/SAVE_BEHAVIOR_REPORTS_SUSTAINED'
export const SAVE_PERSONA_NOTIFICATIONS = 'persona/SAVE_PERSONA_NOTIFICATIONS'


